name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test_skimage_linux:
    name: linux-cp${{ matrix.python-version }}-${{ matrix.OPTIONS_NAME }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependency binaries
        id: cache-bin
        uses: actions/cache@v3
        with:
          key: bin
          path: |
            ~/.local/bin
            ~/.cache/pip

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version}}

      - name: Install package
        run: |
          pip install .

      - name: Install test dependencies
        run: |
          export BIN=~/.local/bin

          pip install pytest antspyx

          mkdir -p $BIN
          cd /tmp

          if [[ ! -f $BIN/greedy ]]; then
              curl -o greedy.tgz -L -s https://sourceforge.net/projects/greedy-reg/files/Nightly/greedy-nightly-Linux-gcc64.tar.gz/download
              tar xf greedy.tgz
              cp greedy*/bin/greedy $BIN/greedy
          fi

          if [[ ! -f $BIN/c3d ]]; then
              curl -o c3d.tgz -L -s https://sourceforge.net/projects/c3d/files/c3d/Nightly/c3d-nightly-Linux-gcc64.tar.gz/download
              tar xf c3d.tgz
              cp c3d*/bin/c3d $BIN/c3d
          fi

      - name: Run tests
        run: |
          pytest tests
